;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-environment
	LaTeX-insert-item
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-insert-sub-or-superscript
	beginning-of-buffer
	beginning-of-visual-line
	end-of-visual-line
	ignore
	ignore-preserving-kill-region
	indent-for-tab-command
	kill-region
	lsp-signature-stop
	magit-stage
	move-text-down
	move-text-up
	org-beginning-of-line
	org-cycle
	org-deadline
	org-end-of-line
	org-insert-heading-respect-content
	org-insert-link
	org-insert-todo-subheading
	org-kill-line
	org-meta-return
	org-metaright
	org-self-insert-command
	org-todo
	org-yank
	overwrite-mode
	undefined
	))

(setq mc/cmds-to-run-once
      '(
	counsel-M-x
	kill-visual-line
	lsp-ui-doc--handle-mouse-movement
	org-delete-char
	org-insert-todo-heading-respect-content
	org-shiftcontrolright
	))
