;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	TeX-insert-backslash
	beginning-of-visual-line
	end-of-visual-line
	move-text-up
	org-beginning-of-line
	org-kill-line
	org-self-insert-command
	org-yank
	xref-pop-marker-stack
	))

(setq mc/cmds-to-run-once
      '(
	))
