;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	comment-line
	indent-for-tab-command
	keyboard-escape-quit
	overwrite-mode
	sh-assignment
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	))
