;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-semi&comma
	c-electric-slash
	c-indent-line-or-region
	comment-line
	f90-electric-insert
	indent-for-tab-command
	keyboard-escape-quit
	magit-gitignore
	magit-gitignore-in-topdir
	move-text-down
	move-text-up
	org-self-insert-command
	overwrite-mode
	sh-assignment
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	))
